### ISSUE TITLE
Update MultiQC

### ISSUE THREAD

**Issue by jfnavarro** [nf-core/sarek#193]
There seems to be an issue with the MultiQC report as most of the stats are not being shown (JavaScript error). Apparently, it is an issue with the parsing of the JSON data. I attached the report from a test run. 
[report.zip](https://github.com/nf-core/sarek/files/4509163/report.zip)

**Comment by ewels** [comment]
I've tracked down the problem here after a bit of debugging. The JSON being produced by MultiQC via the Python `json` library includes `Infinity` values. Apparently this is valid JavaScript but not valid JSON, so it breaks the browser's JSON parsing and the whole report crashes.

I already had code in MultiQC to replace `NaN` for the same reason, so I just need to extend it to also replace `Infinity` and `-Infinity`.

@jfnavarro - if you can send me your `Strelka_G12_2_S191_variants.TsTv.qual` file that would be very helpful, as then I can confirm that my fix works.

Phil

**Comment by ewels** [comment]
Looks like @alneberg found the same problem for VCFTools last year: https://github.com/ewels/MultiQC/issues/894

That fix was for the module though, so didn't solve the problem for all MultiQC tools. I think my fix should work for anything.

**Comment by ewels** [comment]
Ah no, this is still VCFTools producing this error I realise now. And the report you sent @jfnavarro is from MultiQC v1.7.

So this is already fixed in v1.8 if you update MultiQC @MaxUlysse.

I will still keep my more general fix anyway I think 👍

**Comment by ewels** [comment]
Ok, tested by removing @alneberg's fix to replicate the error, then trying my fix. That worked, so now merged and we have double fixes!

**Comment by ewels** [comment]
Ah, MultiQC has already been bumped to v1.8 in `dev`, so this is already fixed ⭐

**Comment by ewels** [comment]
@jfnavarro - if you re-run the development version of Sarek then this problem should be resolved.

**Comment by jfnavarro** [comment]
The problem still occurs with the dev version of Sarek. MultiQC is now 1.8 but it still seems to have problems parsing the data.

**Comment by ewels** [comment]
Can you attach the new report please?

**Comment by ewels** [comment]
And also as above - if you can send me your `Strelka_G12_2_S191_variants.TsTv.qual` file that would be very helpful.

**Comment by jfnavarro** [comment]
[MultiQC.zip](https://github.com/nf-core/sarek/files/4520827/MultiQC.zip)

[Strelka_G12_2_S191_variants.TsTv.qual.zip](https://github.com/nf-core/sarek/files/4520838/Strelka_G12_2_S191_variants.TsTv.qual.zip)

**Comment by ewels** [comment]
Confirmed that this file works fine with the current version of MultiQC 👍  - sounded like you got it running recently though? So we're all good now I think 😄

**Comment by jfnavarro** [comment]
Oh yes, I forgot to post it here. This issue is not present in the current (unreleased) version of MultiQC :) :)
